import React from "react";

export const meta = () => [
  { title: "Terms of Service | Dash Realty" },
  { name: "description", content: "Terms of Service for Dash Realty. Learn about our terms and conditions for using our services." },
  { name: "robots", content: "index, follow" },
  { property: "og:title", content: "Terms of Service | Dash Realty" },
  { property: "og:description", content: "Terms of Service for Dash Realty. Learn about our terms and conditions for using our services." },
  { property: "og:type", content: "website" },
  { rel: "canonical", href: "https://dashrealty.com/terms-of-service" }
];

export default function TermsOfService() {
  return (
    <div className="flex flex-col items-center bg-base-200 min-h-screen pt-8 px-4 w-full">
      <h1 className="text-center text-5xl font-bold mt-12 mb-4">Terms of Service</h1>
      
      <div className="container mx-auto px-4 max-w-4xl">
        <article className="dom-wrap f-col bg-base-100 rounded-lg p-8 shadow-lg">
          <div>
            <div className="mb-6 text-center">
              <p className="text-lg font-medium text-primary mb-2">Dash Realty</p>
              <span className="inline-block text-sm font-semibold bg-base-200 text-base-content rounded px-3 py-1">Last Updated: April 22, 2024</span>
            </div>
            <p>Welcome and thank you for your interest in this website and any subdomains of this website (collectively, the "Website") for Dash Realty ("us," "we," "our," and the "Company"). By clicking a registration or new account submission button, or by otherwise using services on our websites, networks, mobile applications, or other services provided (collectively, the "Services"), or accessing any content provided by us through the Services, you agree to be bound by the following terms of service, as updated from time to time (these "Terms of Service"), which forms a legally binding agreement between you and Dash Realty and its applicable subsidiaries and/or affiliates.</p>
            <p>These Terms of Service apply to your access to and use of the Services, and the information, and products available through the Services.</p>

            <h2 className="mt-8 text-xl font-bold">Updates and Effective Date</h2>
            <p>At any time, and without notice to you, we may update these Terms of Service to reflect changes in our products or services, technology, and uses of data. If you object to any of the changes we make, your choice is to stop using our Services. Your continued use of our Services after such changes are posted will constitute your agreement to and acceptance of such changes.</p>

            <h2 className="mt-8 text-xl font-bold">Privacy Policy</h2>
            <p>Our <a href="#privacy-policy" rel="noopener noreferrer" className="underline">Privacy Policy</a> is incorporated herein by reference.</p>

            <h2 className="mt-8 text-xl font-bold">Disclaimer</h2>
            <p>This Website is provided "as is" without a warranty of any kind, either expressed or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose or non-infringement. Our Services may include inaccuracies or typographical errors. Changes and additions are routinely made to the information herein. We may make additions and/or changes to our Services described herein at any time.</p>

            <h2 className="mt-8 text-xl font-bold">Eligibility Requirements</h2>
            <p>You represent and warrant that you are at least eighteen (18) years of age and that you have the right, authority, and capacity to enter into, perform your obligations under, and abide by these Terms of Service. If you are under the age of 18, you may not, under any circumstances or for any reason, use the Services.</p>
            <p>We may, in our sole discretion, refuse to offer the Services to any person or entity and change its eligibility criteria at any time. You are solely responsible for ensuring that your use of the Services under these Terms of Service is compliant with all laws, rules, and regulations applicable to you. The right to access the Services is revoked where use of the Services is prohibited or to the extent offering, sale or provision of the Services conflicts with any applicable law, rule, or regulation. Further, unless otherwise mutually agreed in writing, the Services are offered only for your use and not for the use or benefit of any third party; and in any event, each person receiving the benefit of the Services must agree to and abide by these Terms of Service as a condition to our obligations.</p>
            <p>Non-U.S. Users. The Services are controlled and offered by us from our facilities in the United States of America. We make no representations that the Services are appropriate or available for use in other locations. Those who access or use the Services from other jurisdictions do so at their own risk and are responsible for compliance with local law. By providing information in connection with the Services, you consent to the transfer of your information to, and storage of your information in, the United States, the laws of which may not be as stringent as the laws of the country in which you reside.</p>

            <h2 className="mt-8 text-xl font-bold">Registration &amp; Accounts</h2>
            <p>To utilize certain Services, you will be required to register for an account ("Account"). You must provide accurate and complete information and keep your Account information updated. You shall not select or use as a username a name (i) of another person with the intent to impersonate that person; (ii) subject to any rights of a person other than you without appropriate authorization; or (iii) that is otherwise offensive, vulgar, or obscene. You are solely responsible for the activity that occurs on your Account and for keeping your Account password secure. You may never use another person’s user account or registration information for the Services without permission. You must notify us immediately of any change in your eligibility to use the Services, any breach of security, or any unauthorized use of your Account. You should never publish, distribute or post login information for your Account. You shall have the ability to delete your Account through a request made to us.</p>

            <h2 className="mt-8 text-xl font-bold">License Grant</h2>
            <p>Subject to these Terms of Service, we grant each user of the Services a non-exclusive, non-sublicensable, and non-transferable license to access and use the Services and access the listings, insights, reports, and content provided by our Services (collectively, "Content") therein for your personal, non-commercial purposes. Any reproduction, modification, distribution, storage, or other use of the Services, or any Content therein for any other purpose, is expressly prohibited without prior written permission from us. You shall not sell, license, rent, share, publish, or otherwise use or exploit any Content outside the Services for commercial use, in connection with the provision of Services to a third party, or in any way that violates the rights of any third party.</p>

            <h2 className="mt-8 text-xl font-bold">Managing Communication Preferences</h2>
            <p><strong>Email subscriptions:</strong></p>
            <p>We may send you email to any email address you provide for various informational and marketing purposes. For example, if you save a search, we may send you emails with new homes on the market that match your search. If you save a home, we may keep you posted on status updates such as a price change. When you use our transaction services, we may send you status updates and other information about your transaction. If you have an Account, you can also manage the types of email you receive by following the instructions included in each email we send you or by editing your preferences at this link: <a href="/profile?type=Account" rel="noopener noreferrer" className="underline">https://dashrealty.com/profile?type=Account</a>. Please note that even if you unsubscribe from some email subscriptions, we may still need to email you with important transactional or other information.</p>
            <p><strong>Calls and texts:</strong></p>
            <p>If you choose to register on our Website, you consent to receiving informational and marketing calls (which may use an automatic telephone dialing system) and artificial or prerecorded voice or text messages at the number(s) you provide. Message and data rates may apply for any messages sent to you from us and to us from you. Message frequency may vary. Carriers are not liable for delayed or undelivered messages. You also certify that the number provided is your phone number and not a number that belongs to anyone else. You release us from any possible liability or claim stemming from our use of your phone number, including but not limited to claims arising from the Telephone Consumer Protection Act. You understand that you are not required to provide this consent and authorization and that it is not a condition to qualify for a loan or to receive any good or service. If you would like to opt out of receiving phone calls from us, please send an email to info@dashrealty.com with the necessary information.</p>
            <p>Your information will only be shared with our mortgage partner if you have indicated upon registration or form submission that you would like to receive mortgage services. Otherwise, your information will only be shared according to our <a href="#privacy-policy" rel="noopener noreferrer" className="underline">Privacy Policy</a>.</p>
            <p>If you do not wish to receive text messages, you may opt out by responding with the SMS message "unsubscribe" to any text message you receive from us. We will send you an SMS message to confirm that you have unsubscribed and after this you will no longer receive SMS messages from us.</p>

            <h2 className="mt-8 text-xl font-bold">Availability of Content</h2>
            <p>We do not guarantee that any Content will be made available through the Services. We reserve the right, but not the obligation, to (i) remove, edit, or modify any Content in our sole discretion, at any time, without notice to you, and for any reason, or for no reason at all; and (ii) remove or block any Content from the Services.</p>

            <h2 className="mt-8 text-xl font-bold">Rules of Conduct</h2>
            <p>As a condition of use, you shall not use the Services for any purpose that is prohibited by these Terms of Service. You are responsible for all of your activity in connection with the Services.</p>
            <p>You shall not (i) impermissively manipulate the price or description of any Listing; (ii) interfere with other users’ Listings; (iii) recruit, solicit, or encourage any other user to use third party services or websites that are competitive to ours; (iv) use the Services to find a Listing, Landlord, Buyer, Seller, or Renter and then complete a transaction independent of the Services in order to circumvent the obligation to pay any fees related to our provision of the Services; (v) take any action that imposes or may impose (as determined by us in our sole discretion) an unreasonable or disproportionately large load on our or our third party providers’ infrastructure; (vi) interfere or attempt to interfere with the proper working of the Services or any activities conducted in connection with the Services; (vii) bypass, circumvent or attempt to bypass or circumvent any measures we may use to prevent or restrict access to the Services (or other accounts, computer systems or networks connected to the Services); (viii) run any form of auto-responder or "spam" on the Services; (ix) use manual or automated software, devices, or other processes to "crawl" or "spider" any page of the Website; (x) harvest or scrape any Content from the Services; (xi) take any action in violation of our guidelines and policies; (xii) decipher, decompile, disassemble, reverse engineer, or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Services, except to the limited extent that applicable laws specifically prohibit such restriction; (xiii) modify, translate, or otherwise create derivative works of any part of the Services; (xiv) infringe any patent, trademark, trade secret, copyright, right of publicity, or other right of any other person or entity or violates any law or contractual duty (see our DMCA Copyright Policy); or (xv) copy, rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder. You shall abide by all applicable local, state, national, and international laws and regulations.</p>
            <p>Our Additional Rights. We also reserve the right, without any obligation, to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request; (ii) enforce these Terms of Service, including investigation of potential violations hereof; (iii) detect, prevent, or otherwise address fraud, security or technical issues; (iv) respond to user support requests; (v) fulfill your requests for services; or (vi) protect the rights, property or safety of us, our users, and the public.</p>

            <h2 className="mt-8 text-xl font-bold">Equal Housing Opportunity</h2>
            <p>We fully support the principles of the Fair Housing Act (Title VIII of the Civil Rights Act of 1968), as amended, which generally prohibits discrimination in the sale, rental, and financing of dwellings, and in other housing-related transactions, based on race, color, national origin, religion, sex, familial status (including children under the age of 18 living with parents of legal custodians, pregnant women, and people securing custody of children under the age of 18), and handicap (disability).</p>

            <h2 className="mt-8 text-xl font-bold">User Content</h2>
            <p>All Content provided by users (collectively "User Content"), whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such User Content. You represent that all User Content provided by you is accurate, complete, up-to- date, and in compliance with all applicable laws, rules, and regulations.</p>
            <p>The following standards apply to any and all User Content. You must ensure that all User Content posted by you complies with all applicable laws and regulations. Without limiting the foregoing, you must not post User Content that:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>infringes any right of any other person or entity or violates any law or contractual duty;</li>
              <li>you know is false, misleading, untruthful, or inaccurate; is unlawful, threatening, discriminatory, hateful, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another’s privacy, tortious, obscene, vulgar, pornographic, offensive, or profane; contains or depicts nudity or sexual activity; promotes bigotry, racism, hatred, or harm against any individual or group; or is otherwise inappropriate as determined by us in our sole discretion;</li>
              <li>constitutes unauthorized or unsolicited advertising, junk, or bulk e-mail (i.e. spamming);</li>
              <li>contains software viruses or any other disabling computer codes, files, or programs that are designed or intended to disrupt, damage, limit, or interfere with the proper function of any software, hardware, or telecommunications equipment, or to damage or obtain unauthorized access to any system, data, password, or other information of ours or of any third party;</li>
              <li>impersonates, bullies, stalks, or intimidates any person or entity, including any of our employees or representatives, or falsifies or misrepresents yourself or your personal information;</li>
              <li>includes any confidential information, violates the rights of others (including, without limitation, the rights of publicity and privacy and rights under a contract), or otherwise contains any material that could give rise to any civil or criminal liability under applicable laws or regulations, or that otherwise may be in conflict with these Terms of Service.</li>
            </ul>
            <p>User Content License Grant. By submitting User Content through the Services, you hereby do and shall grant us a worldwide, non-exclusive, perpetual, royalty-free, fully paid, sublicensable, and transferable license to use, edit, modify, truncate, aggregate, reproduce, distribute, prepare derivative works of, display, perform, and otherwise fully exploit the User Content in connection with the Services and our (including successors’ and assigns’) businesses, including, without limitation, for promoting and redistributing part or all of the Services (and derivative works thereof) in any media formats and through any media channels (including, without limitation, third party websites and feeds), and including after your termination of your Account or the Services. For clarity, the foregoing license grants do not affect your other ownership or license rights in your User Content. You represent and warrant that you have all rights to grant such licenses to us without infringement or violation of any third party rights.</p>

            <h2 className="mt-8 text-xl font-bold">Intellectual Property Rights</h2>
            <p>You acknowledge and agree that the Services and the Content, including User Content owned by us, our licensors, or other providers of such material and are protected by United States and international intellectual property or proprietary rights laws.</p>
            <p>No right, title, or interest in or to the Services or any Content provided in connection with the Services is transferred or otherwise granted to you under these Terms of Service. All right, title, or interest in or to the Services and the Content provided in connection with the Services (other than user contributions posted by you) are reserved by us. Any use of the Services not expressly permitted by these Terms of Service is a breach of these Terms of Service and may violate other laws.</p>
            <p>The names, logos, product and service names, designs, slogans, and other trademarks associated with the Services are ours and those of our licensors. You must not use any of the foregoing without our prior written permission. All other names, logos, product and service names, designs, slogans, and other trademarks used in connection with the Services are the trademarks of their respective owners.</p>

            <h2 className="mt-8 text-xl font-bold">Copyrights</h2>
            <p>The Services may contain Content specifically provided by us, our partners, or our users, and such Content is protected by copyrights, trademarks, service marks, patents, trade secrets, or other proprietary rights and laws. You shall abide by and maintain all copyright notices, information, and restrictions contained in any Content accessed through the Services.</p>

            <h2 className="mt-8 text-xl font-bold">Links To Other Websites</h2>
            <p>Our Services may contain links to third-party websites or services that are not owned or controlled by us. Any such links to third party sites are provided as merely a convenience to the users of the Services, and such links do not imply endorsement of such other third party sites or the content contained therein. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third party websites or services. You further acknowledge and agree that we are not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such websites or services. We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>

            <h2 className="mt-8 text-xl font-bold">Termination</h2>
            <p>We may terminate your access to all or any part of the Services at any time, with or without cause, with or without notice, and effective immediately, which may result in the forfeiture and destruction of all information associated with your membership. If you wish to terminate your Account, you may do so by following the instructions on the Site or through the Services. Any fees paid hereunder are non-refundable. All provisions of these Terms of Service which by their nature should survive termination shall survive termination, including, without limitation, licenses of User Content, ownership provisions, warranty disclaimers, indemnity and limitations of liability, and arbitration.</p>

            <h2 className="mt-8 text-xl font-bold">Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless Dash Realty, its affiliates, and its respective directors, officers, employees, and agents from any and all claims and demands made by any third party due to or arising out of: (a) your access to or use of the Services; (b) your breach of these Terms of Use; (c) your violation of any law or the rights of a third party; (d) any dispute or issue between you and any third party; (e) any User Materials you upload to, or otherwise make available through, the Services; (f) your willful misconduct; and (g) any other party’s access to or use of the Services using your account and password. We reserve the right, at your own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in that case, you agree to corporate with the Companies’ defense of that claim.</p>

            <h2 className="mt-8 text-xl font-bold">No Warranties</h2>
            <p>WE PROVIDE THE SERVICES "AS IS," "WITH ALL FAULTS" AND "AS AVAILABLE," AND THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY, AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY AND ITS SUPPLIERS MAKE NO REPRESENTATIONS, WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED. THE COMPANY AND ITS SUPPLIERS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OR CONDITIONS, EXPRESS, STATUTORY AND IMPLIED, INCLUDING WITHOUT LIMITATION: (A) WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, WORKMANLIKE EFFORT, ACCURACY, TITLE, QUIET ENJOYMENT, NO ENCUMBRANCES, NO LIENS AND NON-INFRINGEMENT; (B) WARRANTIES OR CONDITIONS ARISING THROUGH COURSE OF DEALING OR USAGE OF TRADE; AND (C) WARRANTIES OR CONDITIONS OF UNINTERRUPTED OR ERROR-FREE ACCESS OR USE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU THROUGH THE SERVICES OR ANY MATERIALS AVAILABLE THROUGH THE SERVICES WILL CREATE ANY WARRANTY REGARDING ANY COMPANY ENTITY OR THE SERVICES THAT IS NOT EXPRESSIVELY STATED IN THESE TERMS OF USE. YOU ASSUME ALL RISK FOR ANY DAMAGE THAT MAY RESULT FROM YOUR USE OF OR ACCESS TO THE SERVICES, YOUR DEALING WITH ANY OTHER USER, AND ANY MATERIALS, INCLUDING ALL USER AND COMPANY MATERIALS, AVAILABLE THROUGH THE SERVICES. YOU UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICES, AND USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAINMENT OF MATERIALS THROUGH THE SERVICES AND ANY ASSOCIATED SITES OR SERVICES, ARE AT YOUR OWN DISCRETION AND RISK, AND THAT YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM OR MOBILE DEVICE USED IN CONNECTION WITH THE SERVICES), OR THE LOSS OF DATA THAT RESULTS FROM THE USE OF THE SERVICES OR THE DOWNLOAD OR USE OF THOSE MATERIALS. SOME JURISDICTIONS MAY PROHIBIT A DISCLAIMER OR WARRANTIES AND YOU MAY HAVE OTHER RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.</p>
            <p>We provide the material available through our Website, mobile application and services for informational purposes only. Before you act on any information you have found on the Services, you should independently confirm any facts that are important to your decision. For example, the availability and pricing of any real estate listing is subject to change, and you should contact the appropriate listing agent or other real estate professional to verify pricing information and other aspects of the listing. IF YOU RELY ON ANY INFORMATION, PRODUCT, OR SERVICE AVAILABLE THROUGH OUR SERVICES, YOU EXPRESSLY AGREE THAT YOU DO SO SOLELY AT YOUR OWN RISK. YOU UNDERSTAND THAT YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE OR LOSS YOU MAY INCUR THAT RESULTS FROM YOUR USE OF ANY INFORMATION, PRODUCT OR SERVICE.</p>

            <h2 className="mt-8 text-xl font-bold">Limitation of Liability</h2>
            <p>LIABILITY LIMITS. IN NO EVENT SHALL WE, OR OUR AFFILIATES AND EACH OF OUR AND OUR AFFILIATS’ RESPECTIVE EMPLOYEES, CONTRACTORS, DIRECTORS, SUPPLIERS, LICENSORS, AND REPRESENTATIVES, BE LIABLE UNDER CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE, OR ANY OTHER LEGAL OR EQUITABLE THEORY WITH RESPECT TO THE SERVICES FOR ANY LOST PROFITS, DATA LOSS, COST OF PROCUREMENT OF SUBSTITUTE GOODS, ACCOMMODATIONS, RIGHTS OR SERVICES, OR SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, COMPENSATORY, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER, SUBSTITUTE GOODS OR SERVICES (HOWEVER ARISING), OR FOR ANY DIRECT DAMAGES IN EXCESS OF (IN THE AGGREGATE) THE LESSER OF (A) FEES PAID TO US FOR THE PARTICULAR SERVICES DURING THE IMMEDIATELY PREVIOUS THREE (3) MONTH PERIOD OR (B) $100.00.</p>
            <p>ACKNOWLEDGEMENT. YOU SPECIFICALLY ACKNOWLEDGE THAT WE SHALL NOT BE LIABLE FOR (I) USER CONTENT; (II) THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY; OR (III) THE CONDITION, LEGALITY, OR SUITABILITY OF ANY PROPERTY, AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS SOLELY AND ENTIRELY WITH YOU.</p>
            <p>Releases. You shall and hereby do release us from all liability for you having acquired or not acquired housing through the Services. You hereby release us and our directors, officers, employees, agents, subsidiaries, affiliates, successors, predecessors, assigns, heirs, service providers, insurers, investors, attorneys, advisors, and suppliers from all claims, demands, and damages of every kind and nature, known and unknown, direct and indirect, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to content accessed through the Services, or any interactions with others arising out of or related thereto. You do hereby assume the above mentioned risks and agree that these Terms of Service, and specifically, this Releases provision, shall apply to all unknown or unanticipated results of the transactions and occurrences described above, as well as those known and anticipated, and you hereby knowingly waive any and all rights and protections under <a href="https://codes.findlaw.com/ca/civil-code/civ-sect-1542.html" target="_blank" rel="noopener noreferrer" className="underline">California Civil Code Section 1542</a>, and any similar such provision in any jurisdiction, which section has been duly explained and read as follows: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor."</p>

            <h2 className="mt-8 text-xl font-bold">Governing Law and Jurisdiction</h2>
            <p>These Terms of Service shall be governed by and construed in accordance with the laws of the state of Arizona, including its conflicts of law rules, in the United States of America, and the United Nations Convention on Contracts for the International Sale of Goods shall not be applicable hereto. Without limiting the arbitration obligations set forth above, you agree to submit to the jurisdiction and venue of the state and Federal courts of Maricopa County, Arizona for the purposes of these Terms of Service.</p>
            <p>YOU AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES OR US MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, ANY SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>

            <h2 className="mt-8 text-xl font-bold">GDPR</h2>
            <p>This Website is intended solely for individuals residing outside of the European Union and United Kingdom (UK). By accessing and using this Website, you hereby agree and represent either (i) you are not a resident of the European Union/UK, or (ii) if you are a resident of the European Union/UK, that you hereby provide express consent to any personal information which may be collected from you by this Website, including, but not limited to, first name, last name, email address, phone number, physical address, IP address, and social media accounts and information. In no event shall any user cause this Site to collect personal information of any individual residing in the European Union without first obtaining the express consent of such individual.</p>

            <h2 className="mt-8 text-xl font-bold">User Disputes</h2>
            <p>We reserve the right, without any obligation, to intervene in or monitor disputes between our users. You agree to cooperate with and assist us in good faith, and to provide us with such information and take such actions as we may reasonably request, in connection with any disputes involving you. Although we may moderate content or disputes in our discretion, we have no authority to legally bind third parties or force them to resolve complaints or disputes. Any efforts or statements made by us to intervene in or moderate disputes is superseded by this provision.</p>

            <h2 className="mt-8 text-xl font-bold">Feedback</h2>
            <p>Your feedback, comments and suggestions for improvements to the Services and our business ("Feedback") are generally welcome. You may submit Feedback via our Website, email or AI assistant. You acknowledge and agree that all Feedback is and shall be our sole and exclusive property, and you shall and hereby do assign to us all right, title, and interest in and to all Feedback. You will execute documents and take such further acts as we may reasonably request to effectuate the foregoing ownership and rights.</p>

            <h2 className="mt-8 text-xl font-bold">Modification</h2>
            <p>We reserve the right, in our sole discretion, to modify or replace any of these Terms of Service or change, suspend, limit, or discontinue the Services (including, without limitation, the availability of any feature, database, or content) at any time. If such modification is material, we will post a notice on the Site or send you notice by another appropriate means of electronic communication. It is your responsibility to check these Terms of Service periodically for changes. Your continued use of the Services following posting or notification of any changes to these Terms of Service constitutes acceptance of those changes.</p>

            <h2 className="mt-8 text-xl font-bold">Miscellaneous</h2>
            <p>Entire Agreement. These Terms of Service, together with any state-mandated disclosure forms provided by us to you separately, are the entire agreement between you and us with respect to the Services and supersede all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and us with respect to the Services.</p>

            <h2 className="mt-8 text-xl font-bold">Contact</h2>
            <p>If you have any questions, complaints, or claims with respect to the Services, you may contact us using the information below:</p>
            <p>Address: 13276 Research Blvd, Suite # 107, Austin, Texas, 78750, United States</p>
            <p>Phone: +1(512) 970-6493</p>
            <p>Email: info@dashrealty.com</p>
          </div>
        </article>
        {/* Back to Home */}
        <div className="text-center mt-12">
          <a href="/" className="btn btn-primary btn-lg">
            ← Back to Home
          </a>
        </div>
      </div>
    </div>
  );
}